import { createBridgeHost } from "@wasm-fmt/runtime";
import { cp, lstat, mkdir, readFile, readdir, realpath, rm, stat, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute, join, normalize, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";

const DEFAULT_TARGETS = ["bundler", "node", "esm", "web", "vite"];
const TARGETS = new Set(DEFAULT_TARGETS);
const CORE_FUNCTIONS = [
	"wasm_fmt_abi_version",
	"wasm_fmt_alloc",
	"wasm_fmt_reset",
	"wasm_fmt_register_config",
	"wasm_fmt_release_config",
	"wasm_fmt_output",
	"wasm_fmt_error",
];
const CORE_SUFFIXES = new Set([
	"abi_version",
	"alloc",
	"reset",
	"register_config",
	"release_config",
	"output",
	"error",
]);
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const ENDPOINT = /^[A-Za-z_][A-Za-z0-9_]*$/;
const RESERVED_API_NAMES = new Set([
	"await",
	"arguments",
	"break",
	"case",
	"catch",
	"class",
	"const",
	"continue",
	"debugger",
	"default",
	"delete",
	"do",
	"else",
	"enum",
	"eval",
	"export",
	"extends",
	"false",
	"finally",
	"for",
	"function",
	"if",
	"implements",
	"import",
	"in",
	"instanceof",
	"interface",
	"let",
	"new",
	"null",
	"package",
	"private",
	"protected",
	"public",
	"return",
	"static",
	"super",
	"switch",
	"this",
	"throw",
	"true",
	"try",
	"typeof",
	"var",
	"void",
	"while",
	"with",
	"yield",
	"initAsync",
	"initSync",
]);
const GENERATED_HEADER = "// Generated by @wasm-fmt/bindgen. Do not edit this file directly.\n";

/**
 * @param {import("./index.js").BindingsConfig} input
 * @param {import("./index.js").GenerateBindingsOptions} [options]
 * @returns {Promise<import("./index.js").GenerateBindingsResult>}
 */
export async function generateBindings(input, options = {}) {
	const baseDir = resolve(options.baseDir ?? process.cwd());
	const config = normalizeConfig(input, baseDir);
	await validateInputAndOutputPaths(config);
	const adapter = await loadAdapter(config.adapter);

	const wasmBytes = await readFile(config.wasm);
	const module = new WebAssembly.Module(wasmBytes);
	const inspection = inspectModule(module, config.initialize);
	validateSignatures(wasmBytes, inspection);
	const apiExports = discoverApi(adapter, module, inspection.initialize, config.adapter);

	await prepareOutput(config);

	const files = [];
	await copyInput(config.wasm, join(config.outDir, config.wasmFile), files);
	await copyInput(config.adapter, join(config.outDir, config.adapterFile), files);
	await copyInput(config.mainTypes, join(config.outDir, config.mainTypesFile), files);

	for (const asset of config.assets) {
		await copyInput(asset.from, join(config.outDir, asset.to), files);
	}

	const renderOptions = {
		name: config.name,
		wasmFile: config.wasmFile,
		adapterFile: config.adapterFile,
		mainTypesFile: config.mainTypesFile,
		apiExports,
		initialize: inspection.initialize,
		hostImports: inspection.hostImports,
	};

	await writeOutput(join(config.outDir, `${config.name}_factory.js`), renderFactory(renderOptions), files);
	await writeOutput(join(config.outDir, `${config.name}_factory.d.ts`), renderFactoryTypes(renderOptions), files);

	for (const target of config.targets) {
		const output = targetOutput(config.name, target);
		const source = renderTarget(target, renderOptions);
		await writeOutput(join(config.outDir, output), source, files);
	}

	for (const target of ["web", "vite"]) {
		if (!config.targets.includes(target)) continue;
		const output = `${config.name}_${target}.d.ts`;
		const source = renderInitTypes(renderOptions, target);
		await writeOutput(join(config.outDir, output), source, files);
	}

	const wasmTypesOutput = `${config.wasmFile}.d.ts`;
	const wasmTypes = renderWasmTypes(inspection);
	await writeOutput(join(config.outDir, wasmTypesOutput), wasmTypes, files);

	return {
		outDir: config.outDir,
		files,
		endpoints: inspection.endpoints,
		exports: apiExports,
		initialize: inspection.initialize,
		hostImports: inspection.hostImports,
	};
}

/**
 * @param {unknown} input
 * @param {string} baseDir
 */
function normalizeConfig(input, baseDir) {
	assertObject(input, "bindings config");
	if (input.exports !== undefined) {
		throw new Error("bindings config exports are inferred from adapter.create(wasm) and must not be declared");
	}

	const name = requireString(input.name, "name");
	if (!IDENTIFIER.test(name) || RESERVED_API_NAMES.has(name)) {
		throw new Error(`name must be a safe JavaScript identifier; received ${JSON.stringify(name)}`);
	}

	const wasm = resolveInputPath(baseDir, requireString(input.wasm, "wasm"));
	const wasmFile = requireFileName(input.wasmFile ?? basename(wasm), "wasmFile");
	const adapter = resolveInputPath(baseDir, requireString(input.adapter, "adapter"));
	const adapterFile =
		input.adapterFile === undefined ? `${name}_binding.js` : requireFileName(input.adapterFile, "adapterFile");

	assertObject(input.types, "types");
	const mainTypes = resolveInputPath(baseDir, requireString(input.types.main, "types.main"));
	const mainTypesFile =
		input.types.mainFile === undefined ? `${name}.d.ts` : requireFileName(input.types.mainFile, "types.mainFile");

	const outDirValue = input.outDir === undefined ? "pkg" : requireString(input.outDir, "outDir");
	const outDir = resolveInputPath(baseDir, outDirValue);
	if (input.clean !== undefined && typeof input.clean !== "boolean") {
		throw new TypeError("clean must be a boolean");
	}
	const clean = input.clean ?? false;
	const targets = normalizeTargets(input.targets);
	const assets = normalizeAssets(input.assets, baseDir);
	const initialize = normalizeInitialize(input.initialize);

	if (!isInside(baseDir, outDir)) {
		throw new Error("output directory must stay within the config directory");
	}
	if (clean && !isStrictDescendant(baseDir, outDir)) {
		throw new Error("clean output directory must be a strict descendant of the config directory");
	}

	const copiedSources = [wasm, adapter, mainTypes, ...assets.map((asset) => asset.from)];
	if (clean) {
		for (const source of copiedSources) {
			if (isInside(outDir, source)) {
				throw new Error(`cannot clean output directory containing source asset ${source}`);
			}
		}
	}

	const config = {
		baseDir,
		name,
		wasm,
		wasmFile,
		adapter,
		adapterFile,
		mainTypes,
		mainTypesFile,
		outDir,
		clean,
		targets,
		assets,
		initialize,
	};
	validateOutputDestinations(config);
	return config;
}

/**
 * @param {string} adapter
 */
async function loadAdapter(adapter) {
	let adapterModule;
	try {
		adapterModule = await import(pathToFileURL(adapter).href);
	} catch (error) {
		throw new Error(`failed to load formatter adapter ${adapter}`, { cause: error });
	}
	const value = adapterModule.default;
	if (value === null || typeof value !== "object" || typeof value.create !== "function") {
		throw new TypeError(`formatter adapter ${adapter} must default-export an object with create(wasm)`);
	}
	return value;
}

/**
 * Calls the formatter adapter against a disposable build-time instance and
 * uses its enumerable own function properties as the package's public API.
 *
 * @param {{ create(wasm: WebAssembly.Exports, host: import("@wasm-fmt/runtime").BridgeHost): unknown }} adapter
 * @param {WebAssembly.Module} module
 * @param {string | undefined} initialize
 * @param {string} adapterPath
 */
function discoverApi(adapter, module, initialize, adapterPath) {
	const host = createBridgeHost();
	const instance = new WebAssembly.Instance(module, host.imports);
	const wasm = instance.exports;
	if (initialize !== undefined) {
		wasm[initialize]();
	}

	let api;
	try {
		api = adapter.create(wasm, host);
	} catch (error) {
		throw new Error(`formatter adapter ${adapterPath} failed while creating its build-time API`, { cause: error });
	}
	if (api === null || typeof api !== "object") {
		throw new TypeError(`formatter adapter ${adapterPath} create(wasm) must return an object`);
	}

	const names = normalizeApiExports(Object.keys(api));
	for (const name of names) {
		if (typeof api[name] !== "function") {
			throw new TypeError(`formatter adapter API export ${name} must be a function`);
		}
	}
	return names;
}

/**
 * @param {ReturnType<typeof normalizeConfig>} config
 */
async function validateInputAndOutputPaths(config) {
	const inputs = [
		{
			label: "wasm",
			path: config.wasm,
			destination: config.wasmFile,
			requireFile: true,
		},
		{
			label: "adapter",
			path: config.adapter,
			destination: config.adapterFile,
			requireFile: true,
		},
		{
			label: "types.main",
			path: config.mainTypes,
			destination: config.mainTypesFile,
			requireFile: true,
		},
		...config.assets.map((asset, index) => ({
			label: `assets[${index}]`,
			path: asset.from,
			destination: asset.to,
			requireFile: false,
		})),
	];
	const outputs = collectOutputDestinations(config);
	const base = await realpath(config.baseDir);
	const canonicalOutput = resolve(base, relative(config.baseDir, config.outDir));
	const checked = new Set();
	for (const output of outputs) {
		let path = output.path;
		while (path !== config.baseDir && !checked.has(path)) {
			checked.add(path);
			try {
				const info = await lstat(path);
				if (info.isSymbolicLink()) throw new Error(`output path must not contain symbolic links: ${path}`);
			} catch (error) {
				if (error.code !== "ENOENT") throw error;
			}
			path = dirname(path);
		}
	}

	for (const input of inputs) {
		await rejectSourceSymlinks(input.path);
		const canonicalSource = await realpath(input.path);
		if (config.clean && isInside(canonicalOutput, canonicalSource)) {
			throw new Error(`cannot clean output directory containing source asset ${input.path}`);
		}
		const inputStat = await stat(input.path);
		if (input.requireFile && !inputStat.isFile()) {
			throw new TypeError(`${input.label} must be a file: ${input.path}`);
		}
		const ownDestination = resolve(config.outDir, input.destination);
		for (const output of outputs) {
			if (input.path === output.path && ownDestination !== output.path) {
				throw new Error(`${input.label} source collides with generated output ${output.label}: ${input.path}`);
			}
			if (inputStat.isDirectory() && input.path !== output.path && isInside(input.path, output.path)) {
				throw new Error(`${input.label} source directory contains output ${output.label}: ${output.path}`);
			}
			if (inputStat.isDirectory() && ownDestination !== output.path && isInside(ownDestination, output.path)) {
				throw new Error(`${input.label} output directory contains output ${output.label}: ${output.path}`);
			}
		}
	}
}

/** @param {string} path */
async function rejectSourceSymlinks(path) {
	const info = await lstat(path);
	if (info.isSymbolicLink()) throw new Error(`source assets must not contain symbolic links: ${path}`);
	if (!info.isDirectory()) return;
	for (const entry of await readdir(path)) {
		await rejectSourceSymlinks(join(path, entry));
	}
}

/**
 * @param {ReturnType<typeof normalizeConfig>} config
 */
function validateOutputDestinations(config) {
	const outputs = collectOutputDestinations(config);
	const seen = new Map();
	for (const output of outputs) {
		const previous = seen.get(output.path);
		if (previous !== undefined) {
			throw new Error(`output destination collision between ${previous} and ${output.label}: ${output.path}`);
		}
		seen.set(output.path, output.label);
	}
}

/**
 * @param {ReturnType<typeof normalizeConfig>} config
 */
function collectOutputDestinations(config) {
	const outputs = [
		{ label: "factory", path: resolve(config.outDir, `${config.name}_factory.js`) },
		{ label: "factory types", path: resolve(config.outDir, `${config.name}_factory.d.ts`) },
		{ label: "wasmFile", path: resolve(config.outDir, config.wasmFile) },
		{ label: "adapterFile", path: resolve(config.outDir, config.adapterFile) },
		{ label: "types.mainFile", path: resolve(config.outDir, config.mainTypesFile) },
	];
	for (const [index, asset] of config.assets.entries()) {
		outputs.push({
			label: `assets[${index}].to`,
			path: resolve(config.outDir, asset.to),
		});
	}
	for (const target of config.targets) {
		outputs.push({
			label: `target ${target}`,
			path: resolve(config.outDir, targetOutput(config.name, target)),
		});
	}
	for (const target of ["web", "vite"]) {
		if (!config.targets.includes(target)) continue;
		outputs.push({
			label: `${target} types`,
			path: resolve(config.outDir, `${config.name}_${target}.d.ts`),
		});
	}
	outputs.push({
		label: "Wasm types",
		path: resolve(config.outDir, `${config.wasmFile}.d.ts`),
	});
	return outputs;
}

/**
 * @param {WebAssembly.Module} module
 * @param {"auto" | false | string} initializeOption
 */
function inspectModule(module, initializeOption) {
	const imports = WebAssembly.Module.imports(module);
	const hostNames = new Set(["format_embedded", "embedded_result_len", "read_embedded_result"]);
	if (
		imports.length !== 0 &&
		(imports.length !== 3 ||
			imports.some(
				(item) => item.module !== "wasm_fmt_host" || item.kind !== "function" || !hostNames.delete(item.name),
			))
	) {
		throw new Error("Bridge guest must have zero imports or the complete wasm_fmt_host function group");
	}

	const moduleExports = WebAssembly.Module.exports(module);
	const exportsByName = new Map(moduleExports.map((item) => [item.name, item.kind]));
	if (exportsByName.get("memory") !== "memory") {
		throw new Error("Bridge guest must export memory");
	}
	for (const name of CORE_FUNCTIONS) {
		if (exportsByName.get(name) !== "function") {
			throw new Error(`Bridge guest must export function ${name}`);
		}
	}

	const endpoints = [];
	for (const item of moduleExports) {
		if (item.kind !== "function" || !item.name.startsWith("wasm_fmt_")) {
			continue;
		}
		const suffix = item.name.slice("wasm_fmt_".length);
		if (CORE_SUFFIXES.has(suffix)) {
			continue;
		}
		if (!ENDPOINT.test(suffix)) {
			throw new Error(`invalid Bridge formatter endpoint export ${item.name}`);
		}
		endpoints.push(item.name);
	}
	endpoints.sort();
	if (endpoints.length === 0) {
		throw new Error("Bridge guest must export at least one formatter endpoint");
	}

	const initialize = resolveInitialize(exportsByName, initializeOption);
	return {
		endpoints,
		hostImports: imports.length !== 0,
		initialize,
	};
}

/**
 * @param {Map<string, string>} exportsByName
 * @param {"auto" | false | string} option
 */
function resolveInitialize(exportsByName, option) {
	if (option === false) {
		return undefined;
	}
	if (option === "auto") {
		return exportsByName.get("_initialize") === "function" ? "_initialize" : undefined;
	}
	if (exportsByName.get(option) !== "function") {
		throw new Error(`configured initializer ${option} is not a Wasm function export`);
	}
	return option;
}

/**
 * @param {ReturnType<typeof normalizeConfig>} config
 */
async function prepareOutput(config) {
	if (config.clean) {
		await rm(config.outDir, { recursive: true, force: true });
	}
	await mkdir(config.outDir, { recursive: true });
}

/**
 * @param {string} source
 * @param {string} destination
 * @param {string[]} files
 */
async function copyInput(source, destination, files) {
	if (resolve(source) === resolve(destination)) {
		return;
	}

	const sourceStat = await stat(source);
	await mkdir(dirname(destination), { recursive: true });
	await cp(source, destination, {
		recursive: sourceStat.isDirectory(),
		force: true,
	});
	files.push(destination);
}

/**
 * @param {string} output
 * @param {string} source
 * @param {string[]} files
 */
async function writeOutput(output, source, files) {
	await mkdir(dirname(output), { recursive: true });
	await writeFile(output, source);
	files.push(output);
}

/**
 * @param {string} target
 * @param {RenderOptions} options
 */
function renderTarget(target, options) {
	switch (target) {
		case "bundler":
			return renderBundler(options);
		case "node":
			return renderNode(options);
		case "esm":
			return renderEsm(options);
		case "web":
			return renderWeb(options);
		case "vite":
			return renderVite(options);
		default:
			throw new Error(`unsupported bindings target ${target}`);
	}
}

/** @param {RenderOptions} options */
function renderFactory(options) {
	const initialize = renderInitialize("__bridge_wasm", options.initialize);
	const properties = options.apiExports
		.map(
			(name) =>
				`\t\t[${JSON.stringify(name)}]: __bridge_require_function(__bridge_api[${JSON.stringify(name)}], ${JSON.stringify(name)}),`,
		)
		.join("\n");
	return `${GENERATED_HEADER}/* @ts-self-types="./${options.name}_factory.d.ts" */
import __bridge_adapter from "./${options.adapterFile}";
import { createBridgeHost as __bridge_create_host } from "@wasm-fmt/runtime";

export function createFormatter(moduleOrBuffer) {
	const __bridge_module = moduleOrBuffer instanceof WebAssembly.Module
		? moduleOrBuffer
		: new WebAssembly.Module(moduleOrBuffer);
	const __bridge_host = __bridge_create_host();
	const __bridge_wasm = new WebAssembly.Instance(__bridge_module, __bridge_host.imports).exports;
${indent(initialize.trimEnd(), 1)}
	const __bridge_api = __bridge_adapter.create(__bridge_wasm, __bridge_host);
	if (__bridge_api === null || typeof __bridge_api !== "object") {
		throw new TypeError("formatter adapter create(wasm, host) must return an object");
	}
	return {
${properties}
	};
}

function __bridge_require_function(value, name) {
	if (typeof value !== "function") throw new TypeError(\`formatter adapter export \${name} must be a function\`);
	return value;
}
`;
}

/** @param {RenderOptions} options */
function renderFactoryTypes(options) {
	return `${GENERATED_HEADER}import type * as Formatter from "./${options.mainTypesFile}";

/** Create an independent formatter, including fresh memory and configuration handles. */
export declare function createFormatter(input: BufferSource | WebAssembly.Module): Pick<typeof Formatter, ${options.apiExports.map((name) => JSON.stringify(name)).join(" | ")}>;
`;
}

/**
 * @param {RenderOptions} options
 */
function renderBundler(options) {
	if (options.hostImports) return renderEsm(options);

	const factory = renderStaticFactory();
	const initialize = renderInitialize("__bridge_wasm", options.initialize);
	const bindings = renderStaticBindings(options.apiExports);

	return `${GENERATED_HEADER}/* @ts-self-types="./${options.mainTypesFile}" */
import * as __bridge_wasm from "./${options.wasmFile}";
import __bridge_adapter from "./${options.adapterFile}";
import { createBridgeHost as __bridge_create_host } from "@wasm-fmt/runtime";

const __bridge_host = __bridge_create_host();
${initialize}${factory}${bindings}`;
}

/**
 * @param {RenderOptions} options
 */
function renderNode(options) {
	const factory = renderStaticFactory();
	const initialize = renderInitialize("__bridge_wasm", options.initialize);
	const bindings = renderStaticBindings(options.apiExports);

	return `${GENERATED_HEADER}/* @ts-self-types="./${options.mainTypesFile}" */
import { readFileSync as __bridge_read_file } from "node:fs";
import __bridge_adapter from "./${options.adapterFile}";
import { createBridgeHost as __bridge_create_host } from "@wasm-fmt/runtime";

const __bridge_bytes = __bridge_read_file(new URL("${options.wasmFile}", import.meta.url));
const __bridge_module = new WebAssembly.Module(__bridge_bytes);
const __bridge_host = __bridge_create_host();
const __bridge_instance = new WebAssembly.Instance(__bridge_module, __bridge_host.imports);
const __bridge_wasm = __bridge_instance.exports;

${initialize}${factory}${bindings}`;
}

/**
 * @param {RenderOptions} options
 */
function renderEsm(options) {
	const factory = renderStaticFactory();
	const initialize = renderInitialize("__bridge_wasm", options.initialize);
	const bindings = renderStaticBindings(options.apiExports);

	return `${GENERATED_HEADER}/* @ts-self-types="./${options.mainTypesFile}" */
// prettier-ignore
import source __bridge_module from "./${options.wasmFile}";
import __bridge_adapter from "./${options.adapterFile}";
import { createBridgeHost as __bridge_create_host } from "@wasm-fmt/runtime";

const __bridge_host = __bridge_create_host();
const __bridge_instance = new WebAssembly.Instance(__bridge_module, __bridge_host.imports);
const __bridge_wasm = __bridge_instance.exports;

${initialize}${factory}${bindings}`;
}

/**
 * @param {RenderOptions} options
 */
function renderInitialization(options) {
	const liveBindings = renderLiveBindings(options.apiExports);
	const prepareBindings = renderBindingPreparation(options.apiExports);
	const assignBindings = renderBindingAssignments(options.apiExports);
	const initialize = renderInitialize("__bridge_next_wasm", options.initialize);

	return `let __bridge_wasm;
let __bridge_pending;
let __bridge_initializing = false;
${liveBindings}
function __bridge_require_api(value) {
	if (value === null || typeof value !== "object") {
		throw new TypeError("formatter adapter create(wasm) must return an object");
	}
	return value;
}

function __bridge_require_function(value, name) {
	if (typeof value !== "function") {
		throw new TypeError(\`formatter adapter export \${name} must be a function\`);
	}
	return value;
}

function __bridge_not_initialized() {
	throw new Error("WASM module has not been initialized");
}

function __bridge_finalize({ instance, host }) {
	const __bridge_next_wasm = instance.exports;
${indent(initialize.trimEnd(), 1)}
	const __bridge_api = __bridge_require_api(
		__bridge_adapter.create(__bridge_next_wasm, host),
	);
${indent(prepareBindings.trimEnd(), 1)}
${indent(assignBindings.trimEnd(), 1)}
	__bridge_wasm = __bridge_next_wasm;
	return __bridge_wasm;
}

export function initSync(moduleOrBuffer) {
	if (__bridge_wasm !== undefined) return __bridge_wasm;
	if (__bridge_initializing) throw new Error("WASM initialization is already in progress");
	__bridge_initializing = true;
	try {
		const module = moduleOrBuffer instanceof WebAssembly.Module
			? moduleOrBuffer
			: new WebAssembly.Module(moduleOrBuffer);
		const host = __bridge_create_host();
		return __bridge_finalize({ instance: new WebAssembly.Instance(module, host.imports), host });
	} finally {
		__bridge_initializing = false;
	}
}

function __bridge_init_async(load) {
	if (__bridge_wasm !== undefined) return Promise.resolve(__bridge_wasm);
	if (__bridge_pending !== undefined) return __bridge_pending;
	if (__bridge_initializing) return Promise.reject(new Error("WASM initialization is already in progress"));
	__bridge_initializing = true;
	__bridge_pending = Promise.resolve()
		.then(load)
		.then(__bridge_finalize)
		.finally(() => {
			__bridge_pending = undefined;
			__bridge_initializing = false;
		});
	return __bridge_pending;
}
`;
}

/** @param {RenderOptions} options */
function renderWeb(options) {
	return `${GENERATED_HEADER}/* @ts-self-types="./${options.name}_web.d.ts" */
import __bridge_adapter from "./${options.adapterFile}";
import { createBridgeHost as __bridge_create_host } from "@wasm-fmt/runtime";

${renderInitialization(options)}
async function __bridge_load(module, imports) {
	if (typeof Response === "function" && module instanceof Response) {
		if (typeof WebAssembly.instantiateStreaming === "function") {
			try {
				return await WebAssembly.instantiateStreaming(module, imports);
			} catch (error) {
				const validResponse =
					module.ok &&
					(module.type === "basic" || module.type === "cors" || module.type === "default");
				const wrongContentType =
					module.headers.get("Content-Type") !== "application/wasm";
				if (validResponse && wrongContentType) {
					console.warn(
						"\`WebAssembly.instantiateStreaming\` failed because the server did not use the \`application/wasm\` MIME type. Falling back to \`WebAssembly.instantiate\`.",
						error,
					);
				} else {
					throw error;
				}
			}
		}
		return WebAssembly.instantiate(await module.arrayBuffer(), imports);
	}

	const result = await WebAssembly.instantiate(module, imports);
	if (result instanceof WebAssembly.Instance) {
		return { instance: result, module };
	}
	return result;
}

export default function initAsync(input) {
	return __bridge_init_async(async () => {
		let resolvedInput = await input;
		if (resolvedInput === undefined) {
			resolvedInput = new URL("${options.wasmFile}", import.meta.url);
		}
		if (
			typeof resolvedInput === "string" ||
			(typeof Request === "function" && resolvedInput instanceof Request) ||
			(typeof URL === "function" && resolvedInput instanceof URL)
		) {
			resolvedInput = fetch(resolvedInput);
		}
		const host = __bridge_create_host();
		const { instance } = await __bridge_load(await resolvedInput, host.imports);
		return { instance, host };
	});
}
`;
}

/**
 * @param {RenderOptions} options
 */
function renderVite(options) {
	return `${GENERATED_HEADER}/* @ts-self-types="./${options.name}_vite.d.ts" */
import __bridge_init from "./${options.wasmFile}?init";
import __bridge_adapter from "./${options.adapterFile}";
import { createBridgeHost as __bridge_create_host } from "@wasm-fmt/runtime";

${renderInitialization(options)}
export default function initAsync() {
	if (arguments.length !== 0) {
		return Promise.reject(new TypeError("Vite initAsync takes no arguments; use the Web entry point for custom inputs"));
	}
	return __bridge_init_async(async () => {
		const host = __bridge_create_host();
		const instance = await __bridge_init(host.imports);
		return { instance, host };
	});
}
`;
}

/**
 * @param {RenderOptions} options
 */
function renderInitTypes(options, target) {
	const asyncTypes =
		target === "web"
			? `export type InitInput =
	| RequestInfo
	| URL
	| Response
	| BufferSource
	| WebAssembly.Module;

export default function initAsync(
	input?: InitInput | Promise<InitInput>,
): Promise<InitOutput>;`
			: "export default function initAsync(): Promise<InitOutput>;";
	return `${GENERATED_HEADER}import type * as InitOutput from "./${options.wasmFile}";
type InitOutput = typeof InitOutput;

export type SyncInitInput = BufferSource | WebAssembly.Module;

${asyncTypes}
export declare function initSync(input: SyncInitInput): InitOutput;

export * from "./${options.mainTypesFile}";
`;
}

/**
 * @param {{ endpoints: string[], initialize?: string }} inspection
 */
function renderWasmTypes(inspection) {
	const lines = [GENERATED_HEADER.trimEnd(), "export declare const memory: WebAssembly.Memory;"];
	if (inspection.initialize !== undefined) {
		lines.push(`export declare function ${inspection.initialize}(): void;`);
	}
	lines.push(
		"export declare function wasm_fmt_abi_version(): number;",
		"export declare function wasm_fmt_alloc(size: number): number;",
		"export declare function wasm_fmt_reset(): void;",
		"export declare function wasm_fmt_register_config(id: number, ptr: number, len: number): 1 | 3;",
		"export declare function wasm_fmt_release_config(id: number): void;",
	);
	for (const endpoint of inspection.endpoints) {
		lines.push(`export declare function ${endpoint}(ptr: number, len: number): 0 | 1 | 2 | 3;`);
	}
	lines.push(
		"export declare function wasm_fmt_output(): number;",
		"export declare function wasm_fmt_error(): number;",
		"",
	);
	return lines.join("\n");
}

function renderStaticFactory() {
	return `const __bridge_api = __bridge_require_api(
	__bridge_adapter.create(__bridge_wasm, __bridge_host),
);
`;
}

/**
 * @param {string[]} names
 */
function renderStaticBindings(names) {
	const lines = [
		"function __bridge_require_api(value) {",
		'\tif (value === null || typeof value !== "object") {',
		'\t\tthrow new TypeError("formatter adapter create(wasm) must return an object");',
		"\t}",
		"\treturn value;",
		"}",
		"",
		"function __bridge_require_function(value, name) {",
		'\tif (typeof value !== "function") {',
		"\t\tthrow new TypeError(`formatter adapter export ${name} must be a function`);",
		"\t}",
		"\treturn value;",
		"}",
		"",
	];
	for (const name of names) {
		lines.push(`const __bridge_export_${name} = __bridge_require_function(__bridge_api.${name}, "${name}");`);
		lines.push(`export { __bridge_export_${name} as ${name} };`);
	}
	lines.push("");
	return lines.join("\n");
}

/**
 * @param {string[]} names
 */
function renderLiveBindings(names) {
	const lines = names.flatMap((name) => [
		`let __bridge_binding_${name} = __bridge_not_initialized;`,
		`export { __bridge_binding_${name} as ${name} };`,
	]);
	lines.push("");
	return lines.join("\n");
}

/**
 * @param {string[]} names
 */
function renderBindingPreparation(names) {
	const lines = names.map(
		(name) => `const __bridge_export_${name} = __bridge_require_function(__bridge_api.${name}, "${name}");`,
	);
	lines.push("");
	return lines.join("\n");
}

/**
 * @param {string[]} names
 */
function renderBindingAssignments(names) {
	const lines = names.map((name) => `__bridge_binding_${name} = __bridge_export_${name};`);
	lines.push("");
	return lines.join("\n");
}

/**
 * @param {string} wasm
 * @param {string | undefined} initialize
 */
function renderInitialize(wasm, initialize) {
	if (initialize === undefined) {
		return "";
	}
	return `${wasm}.${initialize}();\n`;
}

/**
 * @param {string} source
 * @param {number} level
 */
function indent(source, level) {
	if (source.length === 0) {
		return "";
	}
	const prefix = "\t".repeat(level);
	return source
		.split("\n")
		.map((line) => (line.length === 0 ? line : `${prefix}${line}`))
		.join("\n");
}

/**
 * @param {string} name
 * @param {string} target
 */
function targetOutput(name, target) {
	switch (target) {
		case "bundler":
			return `${name}.js`;
		case "node":
			return `${name}_node.js`;
		case "esm":
			return `${name}_esm.js`;
		case "web":
			return `${name}_web.js`;
		case "vite":
			return `${name}_vite.js`;
		default:
			throw new Error(`unsupported bindings target ${target}`);
	}
}

/**
 * @param {unknown} value
 */
function normalizeTargets(value) {
	const targets = value === undefined ? [...DEFAULT_TARGETS] : requireArray(value, "targets");
	const result = [];
	const seen = new Set();
	for (const target of targets) {
		if (typeof target !== "string" || !TARGETS.has(target)) {
			throw new Error(`unknown bindings target ${JSON.stringify(target)}`);
		}
		if (seen.has(target)) {
			throw new Error(`duplicate bindings target ${target}`);
		}
		seen.add(target);
		result.push(target);
	}
	if (result.length === 0) {
		throw new Error("targets must not be empty");
	}
	return result;
}

/**
 * @param {unknown} value
 */
function normalizeApiExports(value) {
	const exports = requireArray(value, "exports");
	const result = [];
	const seen = new Set();
	for (const name of exports) {
		if (
			typeof name !== "string" ||
			!IDENTIFIER.test(name) ||
			name.startsWith("__bridge_") ||
			RESERVED_API_NAMES.has(name)
		) {
			throw new Error(`invalid formatter adapter API export ${JSON.stringify(name)}`);
		}
		if (seen.has(name)) {
			throw new Error(`duplicate formatter adapter API export ${name}`);
		}
		seen.add(name);
		result.push(name);
	}
	if (result.length === 0) {
		throw new Error("formatter adapter create(wasm) must expose at least one enumerable function");
	}
	return result;
}

/**
 * @param {unknown} value
 * @param {string} baseDir
 */
function normalizeAssets(value, baseDir) {
	if (value === undefined) {
		return [];
	}
	const assets = requireArray(value, "assets");
	return assets.map((asset, index) => {
		if (typeof asset === "string") {
			const from = resolveInputPath(baseDir, asset);
			return { from, to: basename(from) };
		}
		assertObject(asset, `assets[${index}]`);
		const from = resolveInputPath(baseDir, requireString(asset.from, `assets[${index}].from`));
		const to = asset.to === undefined ? basename(from) : requireRelativeOutput(asset.to, `assets[${index}].to`);
		return { from, to };
	});
}

/**
 * @param {unknown} value
 * @returns {"auto" | false | string}
 */
function normalizeInitialize(value) {
	if (value === undefined || value === "auto") {
		return "auto";
	}
	if (value === false) {
		return false;
	}
	if (typeof value === "string" && IDENTIFIER.test(value) && !RESERVED_API_NAMES.has(value)) {
		return value;
	}
	throw new Error('initialize must be "auto", false, or a safe Wasm function export name');
}

/**
 * @param {unknown} value
 * @param {string} name
 */
function requireString(value, name) {
	if (typeof value !== "string" || value.length === 0) {
		throw new TypeError(`${name} must be a non-empty string`);
	}
	return value;
}

/**
 * @param {unknown} value
 * @param {string} name
 */
function requireFileName(value, name) {
	const result = requireString(value, name);
	if (!/^[A-Za-z0-9_][A-Za-z0-9_.-]*$/.test(result)) {
		throw new Error(`${name} must be a portable file name using letters, digits, underscores, dots, or hyphens`);
	}
	return result;
}

/**
 * @param {unknown} value
 * @param {string} name
 */
function requireRelativeOutput(value, name) {
	const result = requireString(value, name);
	const parts = result.split(/[\\/]/);
	if (
		isAbsolute(result) ||
		parts.includes("..") ||
		normalize(result) === "." ||
		result.endsWith("/") ||
		result.endsWith("\\")
	) {
		throw new Error(`${name} must stay within the output directory`);
	}
	return result;
}

/**
 * @param {unknown} value
 * @param {string} name
 */
function requireArray(value, name) {
	if (!Array.isArray(value)) {
		throw new TypeError(`${name} must be an array`);
	}
	return value;
}

/**
 * @param {unknown} value
 * @param {string} name
 */
function assertObject(value, name) {
	if (value === null || typeof value !== "object" || Array.isArray(value)) {
		throw new TypeError(`${name} must be an object`);
	}
}

/**
 * @param {string} baseDir
 * @param {string} value
 */
function resolveInputPath(baseDir, value) {
	return isAbsolute(value) ? value : resolve(baseDir, value);
}

/**
 * @param {string} parent
 * @param {string} child
 */
function isStrictDescendant(parent, child) {
	const path = relative(parent, child);
	return path.length > 0 && path !== ".." && !path.startsWith(`..${sep}`) && !isAbsolute(path);
}

/**
 * @param {string} parent
 * @param {string} child
 */
function isInside(parent, child) {
	const path = relative(parent, child);
	return path.length === 0 || (path !== ".." && !path.startsWith(`..${sep}`) && !isAbsolute(path));
}

/**
 * @typedef {object} RenderOptions
 * @property {string} name
 * @property {string} wasmFile
 * @property {string} adapterFile
 * @property {string} mainTypesFile
 * @property {string[]} apiExports
 * @property {boolean} hostImports
 * @property {string | undefined} initialize
 */

// The engine validates the binary before this reader runs. Reject type forms
// we cannot inspect rather than silently accepting an unverifiable ABI.
function validateSignatures(bytes, inspection) {
	let offset = 8;
	const u32 = () => {
		let value = 0;
		let shift = 0;
		for (;;) {
			const byte = bytes[offset++];
			value += (byte & 127) * 2 ** shift;
			if ((byte & 128) === 0) return value;
			shift += 7;
		}
	};
	const string = () => {
		const length = u32();
		const value = new TextDecoder().decode(bytes.subarray(offset, offset + length));
		offset += length;
		return value;
	};
	const valueTypes = () =>
		Array.from({ length: u32() }, () => {
			const type = bytes[offset++];
			if (![0x7f, 0x7e, 0x7d, 0x7c, 0x7b, 0x70, 0x6f].includes(type)) {
				throw new Error("Bridge requires core value types, without typed references");
			}
			return type;
		});
	const types = [];
	const functions = [];
	const exports = new Map();
	const imports = [];
	while (offset < bytes.length) {
		const section = bytes[offset++];
		const length = u32();
		const end = offset + length;
		if (section === 1) {
			const count = u32();
			for (let i = 0; i < count; i++) {
				if (bytes[offset++] !== 0x60)
					throw new Error("Bridge requires core function types, without GC type declarations");
				types.push([valueTypes(), valueTypes()]);
			}
		} else if (section === 2) {
			const count = u32();
			for (let i = 0; i < count; i++) {
				const module = string();
				const name = string();
				const kind = bytes[offset++];
				if (module !== "wasm_fmt_host" || kind !== 0) throw new Error("unsupported Bridge import");
				const type = u32();
				functions.push(type);
				imports.push({ name, type });
			}
		} else if (section === 3) {
			const count = u32();
			for (let i = 0; i < count; i++) functions.push(u32());
		} else if (section === 7) {
			const count = u32();
			for (let i = 0; i < count; i++) {
				const name = string();
				const kind = bytes[offset++];
				const index = u32();
				if (kind === 0) exports.set(name, index);
			}
		}
		offset = end;
	}
	const signature = (params, results) => [Array(params).fill(0x7f), Array(results).fill(0x7f)];
	const check = (name, type, expected) => {
		if (JSON.stringify(types[type]) !== JSON.stringify(expected)) {
			throw new Error(`invalid ${name} signature`);
		}
	};
	const hostSignatures = {
		format_embedded: signature(2, 1),
		embedded_result_len: signature(0, 1),
		read_embedded_result: signature(2, 0),
	};
	for (const { name, type } of imports) check(`wasm_fmt_host.${name}`, type, hostSignatures[name]);
	const coreSignatures = {
		wasm_fmt_abi_version: signature(0, 1),
		wasm_fmt_alloc: signature(1, 1),
		wasm_fmt_reset: signature(0, 0),
		wasm_fmt_register_config: signature(3, 1),
		wasm_fmt_release_config: signature(1, 0),
		wasm_fmt_output: signature(0, 1),
		wasm_fmt_error: signature(0, 1),
	};
	for (const [name, expected] of Object.entries(coreSignatures)) {
		check(name, functions[exports.get(name)], expected);
	}
	for (const name of inspection.endpoints) check(name, functions[exports.get(name)], signature(2, 1));
	if (inspection.initialize !== undefined) {
		check(inspection.initialize, functions[exports.get(inspection.initialize)], signature(0, 0));
	}
}
